### ISSUE TITLE
Form state should be generic

### ISSUE THREAD

**Issue by rufatZZ** [rust4m/react-kb-form#6]
Right now any desctructed property from `formState` gives an error like `types does not exist on type 'IFormData[]`. But it should be generic object and not array (Right now is `IForm[]` ). Because mostly form state is object. Also inside of the form state object should be more strictly typed generic, Right now it is like  `[name: string]: any;`. `any` should be redunant for strictly type checking.

**I'm submitting a:**

[x] bug report
[ ] feature request

**Related code to the current behavior:**

```tsx
    import { useKBform } from 'react-kb-form';

    const { _register, _handleSubmit, formState, errorState } = useKBform();
    ...
    
    someMethod(formState.eTaxesForm);  // <=  TS2339: Property 'eTaxesForm' does not exist on type 'IFormData[]'.
```

**Comment by rufatZZ** [comment]
I`m making PR for this issue. You can check it out.

**Comment by rust4m** [comment]
merged

**Comment by rufatZZ** [comment]
> merged

Thanks! Do we need to inform other teams  about this feature which uses this library?

**Comment by rust4m** [comment]
yes, we should inform them
